Create SQL commands intro workshop
foundersandcoders/sql-commands-intro pull request #1
Opened 2017-07-28 18:54 UTC by macintoshhelper

Has 7 questions/tasks currently.
Has some links for accompanied resources.

Not sure if it's long enough yet?

#291

2017-07-29 14:21 UTC, jsms90 commented
@macintoshhelper This seems like a recreation of the [existing exercises](https://pgexercises.com/questions/basic/) that students are pointed to?

2017-07-29 14:32 UTC, macintoshhelper commented
@jsms90 The data is more "real world" - I find it's harder to learn SQL if using more abstract data. I tried to cover similar content, since I feel it progresses nicely.

2017-07-30 20:46 UTC, shiryz requested changes
Looks really good, one small change

2017-07-30 20:46 UTC, shiryz commented on README.md
> +Make sure you have installed and setup PostgreSQL.
Add a link to installation instructions, [DWYL's learn ppostgres](https://github.com/dwyl/learn-postgresql)

2017-07-30 20:50 UTC, macintoshhelper commented on README.md
> +Make sure you have installed and setup PostgreSQL.
I've added a link to my installation instructions (proposed change in `master-reference`).

2017-07-30 20:53 UTC, shiryz approved these changes

2017-07-30 21:18 UTC, jsms90 requested changes
Minor thing.

Looks great @macintoshhelper

2017-07-30 21:18 UTC, jsms90 commented on README.md
> +## Syntaxes
This section seems a bit redundant. You have the same information in  "Setting up the workshop database"

2017-07-30 21:25 UTC, shiryz approved these changes

2017-07-30 21:36 UTC, macintoshhelper commented on README.md
> +## Syntaxes
Replaced it with workshop-specific info.

2017-07-30 21:50 UTC, jsms90 commented on README.md
> +## Syntaxes
Sorry, this comment refers to the whole "Syntaxes" section.

2017-07-30 21:56 UTC, macintoshhelper commented on README.md
> +## Syntaxes
Ok, I've removed syntaxes

2017-07-30 22:02 UTC, jsms90 approved these changes

2017-07-30 22:02 UTC, merged