Move solutions file to master - #5
foundersandcoders/sql-commands-intro pull request #6
Opened 2017-07-30 21:53 UTC by macintoshhelper

2017-07-30 21:56 UTC, jsms90 approved these changes

2017-07-30 21:57 UTC, jsms90 commented
@ConchobarMacNessa @pbywater Should have someone who has actually user tested this workshop be the person to merge the solutions in

2017-07-30 22:04 UTC, jsms90 requested changes
The readme has been removed?

2017-07-31 08:06 UTC, shiryz requested changes
Great work @macintoshhelper , did not catch these changes yesterday, it shouldn't take too long

2017-07-31 08:06 UTC, shiryz commented on README.md
> +7. Using [`CASE WHEN`](https://www.postgresql.org/docs/7.4/static/functions-conditional.html), get a list of user ids from the `users` table and label a new row, `teenager` with `true` or `false`.
Adding a hint for AS would help, they haven't seen how to create a new column before

2017-07-31 08:06 UTC, shiryz commented on README.md
> +10. Using [`INSERT INTO`](https://www.w3schools.com/sql/sql_insert.asp), add a comment with the text `Interesting post` from the user\_id of `3` to the blog post containing the text `Peculiar` (reply
Add a hint for sub-queries, as in *hint*: search sub-queries

2017-07-31 08:08 UTC, jsms90 approved these changes

2017-07-31 11:03 UTC, jsms90 requested changes
@macintoshhelper It currrently looks like a whole readme file is being added, which it's not, because the readme file is already in the master branch.

You need to merge this branch with master.

2017-07-31 15:21 UTC, shiryz approved these changes

2017-08-01 06:07 UTC, jsms90 commented
@macintoshhelper The `init.sql` file is also being removed with this PR

2018-11-28 10:32 UTC, m4v15 commented
closing as superseded by #18

2018-11-28 10:32 UTC, closed without merging